use_frameworks!

platform :ios, '10.0'

target 'NetWork_Example' do
 # pod 'NetWork', :path => '../'

  target 'NetWork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
